In [3]:
import pandas as pd

In [4]:
ons = pd.read_parquet("data/interim/load_clean.parquet")
inmet = pd.read_parquet("data/interim/weather_clean.parquet")

In [5]:
ons.head()

  subsystem_code subsystem           timestamp    load_mw  source_year
0             NE  NORDESTE 2022-01-01 00:00:00  10508.822         2022
1             NE  NORDESTE 2022-01-01 01:00:00  10598.654         2022
2             NE  NORDESTE 2022-01-01 02:00:00  10625.716         2022
3             NE  NORDESTE 2022-01-01 03:00:00  10583.828         2022
4             NE  NORDESTE 2022-01-01 04:00:00  10495.137         2022

In [6]:
inmet.head()

,timestamp,region,precipitation_mm,pressure_station_hpa,pressure_max_hpa,pressure_min_hpa,global_radiation_kj_m2,temperature_c,dew_point_c,temperature_max_c,temperature_min_c,dew_point_max_c,dew_point_min_c,humidity_max_pct,humidity_min_pct,humidity_pct,wind_gust_ms,wind_speed_ms,wind_direction_deg,station_count
0,2022-01-01 00:00:00+00:00,NORDESTE,1.165217,974.582143,974.605357,973.880357,1.620000,23.971429,20.721569,24.460714,23.894643,20.936000,20.372000,82.680000,78.760000,82.392157,4.003704,1.503704,97.753149,144
1,2022-01-01 01:00:00+00:00,NORDESTE,0.339130,976.091379,976.155172,975.739655,68.233333,23.655172,20.926923,24.127586,23.581034,21.175472,20.639623,85.471698,81.981132,84.711538,4.121818,1.352727,104.333533,144
2,2022-01-01 02:00:00+00:00,NORDESTE,0.343478,973.700000,973.919298,973.631579,123.000000,23.119298,20.912245,23.491228,23.068421,21.048980,20.646939,87.208333,84.653061,86.937500,3.680000,1.287273,101.001139,144
3,2022-01-01 03:00:00+00:00,NORDESTE,0.097872,975.218966,975.636207,975.194828,457.171429,23.053448,20.966000,23.387931,22.996552,21.134000,20.800000,88.163265,85.959184,87.816327,3.430909,1.145455,96.908462,144
4,2022-01-01 04:00:00+00:00,NORDESTE,0.114894,973.732143,974.223214,973.712500,306.800000,22.785714,20.923913,23.053571,22.700000,21.095652,20.769565,88.777778,86.911111,88.444444,3.075472,1.056604,106.756377,144

In [7]:
ons.info()

<class 'pandas.DataFrame'>
RangeIndex: 41448 entries, 0 to 41447
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   subsystem_code  41448 non-null  string
 1   subsystem       41448 non-null  str
 2   timestamp       41448 non-null  datetime64[us]
 3   load_mw         41448 non-null  float64
 4   source_year     41448 non-null  int64
dtypes: datetime64[us](1), float64(1), int64(1), str(1), string(1)
memory usage: 2.0 MB

In [8]:
inmet.info()

<class 'pandas.DataFrame'>
RangeIndex: 40896 entries, 0 to 40895
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   timestamp               40896 non-null  datetime64[us, UTC]
 1   region                  40896 non-null  str
 2   precipitation_mm        40896 non-null  float64
 3   pressure_station_hpa    40896 non-null  float64
 4   pressure_max_hpa        40896 non-null  float64
 5   pressure_min_hpa        40896 non-null  float64
 6   global_radiation_kj_m2  40893 non-null  float64
 7   temperature_c           40896 non-null  float64
 8   dew_point_c             40896 non-null  float64
 9   temperature_max_c       40896 non-null  float64
 10  temperature_min_c       40896 non-null  float64
 11  dew_point_max_c         40896 non-null  float64
 12  dew_point_min_c         40896 non-null  float64
 13  humidity_max_pct        40896 non-null  float64
 14  humidity_min_pct        40896 non-null  float64
 15  humidity_pct            40896 non-null  float64
 16  wind_gust_ms            40896 non-null  float64
 17  wind_speed_ms           40896 non-null  float64
 18  wind_direction_deg      40896 non-null  float64
 19  station_count           40896 non-null  int64
dtypes: datetime64[us, UTC](1), float64(17), int64(1), str(1)
memory usage: 6.6 MB

## Ajustando timestamp

In [9]:
inmet["timestamp"] = inmet["timestamp"].dt.tz_localize(None)

In [10]:
inmet.head()

,timestamp,region,precipitation_mm,pressure_station_hpa,pressure_max_hpa,pressure_min_hpa,global_radiation_kj_m2,temperature_c,dew_point_c,temperature_max_c,temperature_min_c,dew_point_max_c,dew_point_min_c,humidity_max_pct,humidity_min_pct,humidity_pct,wind_gust_ms,wind_speed_ms,wind_direction_deg,station_count
0,2022-01-01 00:00:00,NORDESTE,1.165217,974.582143,974.605357,973.880357,1.620000,23.971429,20.721569,24.460714,23.894643,20.936000,20.372000,82.680000,78.760000,82.392157,4.003704,1.503704,97.753149,144
1,2022-01-01 01:00:00,NORDESTE,0.339130,976.091379,976.155172,975.739655,68.233333,23.655172,20.926923,24.127586,23.581034,21.175472,20.639623,85.471698,81.981132,84.711538,4.121818,1.352727,104.333533,144
2,2022-01-01 02:00:00,NORDESTE,0.343478,973.700000,973.919298,973.631579,123.000000,23.119298,20.912245,23.491228,23.068421,21.048980,20.646939,87.208333,84.653061,86.937500,3.680000,1.287273,101.001139,144
3,2022-01-01 03:00:00,NORDESTE,0.097872,975.218966,975.636207,975.194828,457.171429,23.053448,20.966000,23.387931,22.996552,21.134000,20.800000,88.163265,85.959184,87.816327,3.430909,1.145455,96.908462,144
4,2022-01-01 04:00:00,NORDESTE,0.114894,973.732143,974.223214,973.712500,306.800000,22.785714,20.923913,23.053571,22.700000,21.095652,20.769565,88.777778,86.911111,88.444444,3.075472,1.056604,106.756377,144

In [11]:
inmet.info()

<class 'pandas.DataFrame'>
RangeIndex: 40896 entries, 0 to 40895
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   timestamp               40896 non-null  datetime64[us]
 1   region                  40896 non-null  str
 2   precipitation_mm        40896 non-null  float64
 3   pressure_station_hpa    40896 non-null  float64
 4   pressure_max_hpa        40896 non-null  float64
 5   pressure_min_hpa        40896 non-null  float64
 6   global_radiation_kj_m2  40893 non-null  float64
 7   temperature_c           40896 non-null  float64
 8   dew_point_c             40896 non-null  float64
 9   temperature_max_c       40896 non-null  float64
 10  temperature_min_c       40896 non-null  float64
 11  dew_point_max_c         40896 non-null  float64
 12  dew_point_min_c         40896 non-null  float64
 13  humidity_max_pct        40896 non-null  float64
 14  humidity_min_pct        40896 non-null  float64
 15  humidity_pct            40896 non-null  float64
 16  wind_gust_ms            40896 non-null  float64
 17  wind_speed_ms           40896 non-null  float64
 18  wind_direction_deg      40896 non-null  float64
 19  station_count           40896 non-null  int64
dtypes: datetime64[us](1), float64(17), int64(1), str(1)
memory usage: 6.6 MB

## Verificação de timestamp duplicados

In [15]:
ons['timestamp'].duplicated().sum()

np.int64(0)

In [16]:
inmet['timestamp'].duplicated().sum()

np.int64(0)

## Valores ausentes e outliers

In [17]:
ons.isna().sum()

subsystem_code    0
subsystem         0
timestamp         0
load_mw           0
source_year       0
dtype: int64

In [18]:
inmet.isna().sum()

timestamp                 0
region                    0
precipitation_mm          0
pressure_station_hpa      0
pressure_max_hpa          0
pressure_min_hpa          0
global_radiation_kj_m2    3
temperature_c             0
dew_point_c               0
temperature_max_c         0
temperature_min_c         0
dew_point_max_c           0
dew_point_min_c           0
humidity_max_pct          0
humidity_min_pct          0
humidity_pct              0
wind_gust_ms              0
wind_speed_ms             0
wind_direction_deg        0
station_count             0
dtype: int64

In [19]:
inmet[inmet['global_radiation_kj_m2'].isna()]

,timestamp,region,precipitation_mm,pressure_station_hpa,pressure_max_hpa,pressure_min_hpa,global_radiation_kj_m2,temperature_c,dew_point_c,temperature_max_c,temperature_min_c,dew_point_max_c,dew_point_min_c,humidity_max_pct,humidity_min_pct,humidity_pct,wind_gust_ms,wind_speed_ms,wind_direction_deg,station_count
1872,2022-03-20 00:00:00,NORDESTE,0.000000,973.633333,973.642593,973.031481,NaN,24.407273,20.770833,25.034545,24.305455,21.045833,20.458333,81.959184,77.510204,81.306122,3.309434,1.218868,108.606527,144
2354,2022-04-09 02:00:00,NORDESTE,0.004255,977.747368,977.912281,977.561404,NaN,23.484211,19.918868,24.021053,23.285965,20.298113,19.700000,83.320755,79.716981,82.169811,3.100000,0.947273,84.756851,144
35236,2026-01-08 04:00:00,NORDESTE,0.000000,978.250000,978.837500,978.250000,NaN,23.887500,19.957143,24.437500,23.812500,20.014286,19.728571,79.714286,76.714286,79.571429,4.162500,1.675000,113.061098,135

In [20]:
inmet["global_radiation_kj_m2"] = (
    inmet["global_radiation_kj_m2"]
    .interpolate(method="linear")
)

In [21]:
inmet[inmet['global_radiation_kj_m2'].isna()]

Empty DataFrame
Columns: [timestamp, region, precipitation_mm, pressure_station_hpa, pressure_max_hpa, pressure_min_hpa, global_radiation_kj_m2, temperature_c, dew_point_c, temperature_max_c, temperature_min_c, dew_point_max_c, dew_point_min_c, humidity_max_pct, humidity_min_pct, humidity_pct, wind_gust_ms, wind_speed_ms, wind_direction_deg, station_count]
Index: []

In [23]:
inmet.isna().sum()

timestamp                 0
region                    0
precipitation_mm          0
pressure_station_hpa      0
pressure_max_hpa          0
pressure_min_hpa          0
global_radiation_kj_m2    0
temperature_c             0
dew_point_c               0
temperature_max_c         0
temperature_min_c         0
dew_point_max_c           0
dew_point_min_c           0
humidity_max_pct          0
humidity_min_pct          0
humidity_pct              0
wind_gust_ms              0
wind_speed_ms             0
wind_direction_deg        0
station_count             0
dtype: int64

In [24]:
ons.describe()

                 timestamp       load_mw   source_year
count                41448  41448.000000  41448.000000
mean   2024-05-13 11:30:00  12580.532112   2023.885350
min    2022-01-01 00:00:00   7262.283000   2022.000000
25%    2023-03-08 17:45:00  11544.804750   2023.000000
50%    2024-05-13 11:30:00  12623.361500   2024.000000
75%    2025-07-19 05:15:00  13696.423000   2025.000000
max    2026-09-23 23:00:00  18156.972000   2026.000000
std                    NaN   1520.057541      1.367879

In [25]:
inmet.describe()

,timestamp,precipitation_mm,pressure_station_hpa,pressure_max_hpa,pressure_min_hpa,global_radiation_kj_m2,temperature_c,dew_point_c,temperature_max_c,temperature_min_c,dew_point_max_c,dew_point_min_c,humidity_max_pct,humidity_min_pct,humidity_pct,wind_gust_ms,wind_speed_ms,wind_direction_deg,station_count
count,40896,40896.000000,40896.000000,40896.000000,40896.000000,40896.000000,40896.000000,40896.000000,40896.000000,40896.000000,40896.000000,40896.000000,40896.000000,40896.000000,40896.000000,40896.000000,40896.000000,40896.000000,40896.000000
mean,2024-05-01 23:30:00,0.120756,979.878698,980.152449,979.584285,857.286131,25.927228,19.208373,26.579132,25.307043,19.718624,18.707121,72.594419,67.159271,69.936970,5.170171,1.992793,112.167504,141.134390
min,2022-01-01 00:00:00,0.000000,969.279688,969.428125,969.000000,0.000000,18.226250,12.044186,18.685000,17.813750,12.932558,11.148837,34.236842,30.017699,31.885965,1.558763,0.480392,0.096969,135.000000
25%,2023-03-02 23:45:00,0.007843,978.103713,978.392499,977.814775,42.770170,23.214286,17.631693,23.611241,22.842814,18.122504,17.140363,62.360283,54.858470,58.525256,3.654357,1.336778,92.325037,141.000000
50%,2024-05-01 23:30:00,0.046914,979.887500,980.153153,979.567779,326.799856,25.353734,19.567391,25.967641,24.784746,20.092390,19.012423,75.000000,68.771834,71.980861,4.983673,1.896748,113.294115,141.000000
75%,2025-07-01 23:15:00,0.146032,981.735793,982.000000,981.434375,1706.609451,28.763177,20.826683,29.656551,27.877010,21.277778,20.410657,84.288136,80.250000,82.447467,6.580539,2.583333,131.131319,142.000000
max,2026-08-31 23:00:00,3.059574,989.766216,989.871053,989.277027,3561.058036,35.363265,23.788636,36.161616,34.615152,24.523958,23.194186,94.506667,93.726027,94.253333,10.830526,4.784211,359.726837,144.000000
std,NaN,0.193521,2.846294,2.834403,2.834914,977.770337,3.386135,2.066302,3.592368,3.173543,2.042494,2.117808,13.698548,15.076233,14.472304,1.817589,0.788162,33.234007,2.469827

## Base processed ONS + INMET

In [26]:
processed = pd.merge(ons, inmet, on="timestamp", how="inner")

In [27]:
processed.head()

,subsystem_code,subsystem,timestamp,load_mw,source_year,region,precipitation_mm,pressure_station_hpa,pressure_max_hpa,pressure_min_hpa,...,temperature_min_c,dew_point_max_c,dew_point_min_c,humidity_max_pct,humidity_min_pct,humidity_pct,wind_gust_ms,wind_speed_ms,wind_direction_deg,station_count
0,NE,NORDESTE,2022-01-01 00:00:00,10508.822,2022,NORDESTE,1.165217,974.582143,974.605357,973.880357,...,23.894643,20.936000,20.372000,82.680000,78.760000,82.392157,4.003704,1.503704,97.753149,144
1,NE,NORDESTE,2022-01-01 01:00:00,10598.654,2022,NORDESTE,0.339130,976.091379,976.155172,975.739655,...,23.581034,21.175472,20.639623,85.471698,81.981132,84.711538,4.121818,1.352727,104.333533,144
2,NE,NORDESTE,2022-01-01 02:00:00,10625.716,2022,NORDESTE,0.343478,973.700000,973.919298,973.631579,...,23.068421,21.048980,20.646939,87.208333,84.653061,86.937500,3.680000,1.287273,101.001139,144
3,NE,NORDESTE,2022-01-01 03:00:00,10583.828,2022,NORDESTE,0.097872,975.218966,975.636207,975.194828,...,22.996552,21.134000,20.800000,88.163265,85.959184,87.816327,3.430909,1.145455,96.908462,144
4,NE,NORDESTE,2022-01-01 04:00:00,10495.137,2022,NORDESTE,0.114894,973.732143,974.223214,973.712500,...,22.700000,21.095652,20.769565,88.777778,86.911111,88.444444,3.075472,1.056604,106.756377,144

In [29]:
processed.tail()

,subsystem_code,subsystem,timestamp,load_mw,source_year,region,precipitation_mm,pressure_station_hpa,pressure_max_hpa,pressure_min_hpa,...,temperature_min_c,dew_point_max_c,dew_point_min_c,humidity_max_pct,humidity_min_pct,humidity_pct,wind_gust_ms,wind_speed_ms,wind_direction_deg,station_count
40891,NE,NORDESTE,2026-08-31 19:00:00,15309.979,2026,NORDESTE,0.0,976.298649,976.432432,976.137838,...,30.676316,17.229412,15.919118,46.811594,42.318841,45.246377,7.819118,3.167647,102.857044,140
40892,NE,NORDESTE,2026-08-31 20:00:00,15255.274,2026,NORDESTE,0.0,976.643243,976.656757,976.270270,...,30.010526,17.145588,16.001471,49.434783,44.159420,48.652174,7.513235,3.005882,102.949787,140
40893,NE,NORDESTE,2026-08-31 21:00:00,15686.557,2026,NORDESTE,0.0,977.532857,977.540000,977.131429,...,28.368056,17.210606,16.425758,54.029851,48.402985,53.121212,6.564063,2.329687,100.969863,140
40894,NE,NORDESTE,2026-08-31 22:00:00,15660.982,2026,NORDESTE,0.0,978.015714,978.022857,977.528571,...,27.045833,17.555385,16.753846,58.575758,52.848485,58.363636,5.456250,2.184375,107.139521,140
40895,NE,NORDESTE,2026-08-31 23:00:00,15149.486,2026,NORDESTE,0.0,979.294118,979.295588,978.605882,...,26.148571,18.057143,17.304762,63.171875,58.109375,62.750000,5.508065,2.029032,107.810911,140

In [30]:
len(processed)

40896

In [31]:
processed.info()

<class 'pandas.DataFrame'>
RangeIndex: 40896 entries, 0 to 40895
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   subsystem_code          40896 non-null  string
 1   subsystem               40896 non-null  str
 2   timestamp               40896 non-null  datetime64[us]
 3   load_mw                 40896 non-null  float64
 4   source_year             40896 non-null  int64
 5   region                  40896 non-null  str
 6   precipitation_mm        40896 non-null  float64
 7   pressure_station_hpa    40896 non-null  float64
 8   pressure_max_hpa        40896 non-null  float64
 9   pressure_min_hpa        40896 non-null  float64
 10  global_radiation_kj_m2  40896 non-null  float64
 11  temperature_c           40896 non-null  float64
 12  dew_point_c             40896 non-null  float64
 13  temperature_max_c       40896 non-null  float64
 14  temperature_min_c       40896 non-null  float64
 15  dew_point_max_c         40896 non-null  float64
 16  dew_point_min_c         40896 non-null  float64
 17  humidity_max_pct        40896 non-null  float64
 18  humidity_min_pct        40896 non-null  float64
 19  humidity_pct            40896 non-null  float64
 20  wind_gust_ms            40896 non-null  float64
 21  wind_speed_ms           40896 non-null  float64
 22  wind_direction_deg      40896 non-null  float64
 23  station_count           40896 non-null  int64
dtypes: datetime64[us](1), float64(18), int64(2), str(2), string(1)
memory usage: 8.2 MB

In [32]:
colunas = processed.columns.tolist()

In [33]:
print(colunas)

['subsystem_code', 'subsystem', 'timestamp', 'load_mw', 'source_year', 'region', 'precipitation_mm', 'pressure_station_hpa', 'pressure_max_hpa', 'pressure_min_hpa', 'global_radiation_kj_m2', 'temperature_c', 'dew_point_c', 'temperature_max_c', 'temperature_min_c', 'dew_point_max_c', 'dew_point_min_c', 'humidity_max_pct', 'humidity_min_pct', 'humidity_pct', 'wind_gust_ms', 'wind_speed_ms', 'wind_direction_deg', 'station_count']

In [34]:
processed['region'].unique()

<ArrowStringArray>
['NORDESTE']
Length: 1, dtype: str

In [35]:
processed['subsystem'].unique()

<ArrowStringArray>
['NORDESTE']
Length: 1, dtype: str

In [36]:
processed.drop(columns=['region', 'subsystem'], inplace=True)

In [37]:
processed.head()

,subsystem_code,timestamp,load_mw,source_year,precipitation_mm,pressure_station_hpa,pressure_max_hpa,pressure_min_hpa,global_radiation_kj_m2,temperature_c,...,temperature_min_c,dew_point_max_c,dew_point_min_c,humidity_max_pct,humidity_min_pct,humidity_pct,wind_gust_ms,wind_speed_ms,wind_direction_deg,station_count
0,NE,2022-01-01 00:00:00,10508.822,2022,1.165217,974.582143,974.605357,973.880357,1.620000,23.971429,...,23.894643,20.936000,20.372000,82.680000,78.760000,82.392157,4.003704,1.503704,97.753149,144
1,NE,2022-01-01 01:00:00,10598.654,2022,0.339130,976.091379,976.155172,975.739655,68.233333,23.655172,...,23.581034,21.175472,20.639623,85.471698,81.981132,84.711538,4.121818,1.352727,104.333533,144
2,NE,2022-01-01 02:00:00,10625.716,2022,0.343478,973.700000,973.919298,973.631579,123.000000,23.119298,...,23.068421,21.048980,20.646939,87.208333,84.653061,86.937500,3.680000,1.287273,101.001139,144
3,NE,2022-01-01 03:00:00,10583.828,2022,0.097872,975.218966,975.636207,975.194828,457.171429,23.053448,...,22.996552,21.134000,20.800000,88.163265,85.959184,87.816327,3.430909,1.145455,96.908462,144
4,NE,2022-01-01 04:00:00,10495.137,2022,0.114894,973.732143,974.223214,973.712500,306.800000,22.785714,...,22.700000,21.095652,20.769565,88.777778,86.911111,88.444444,3.075472,1.056604,106.756377,144

In [39]:
processed.isna().sum()

subsystem_code            0
timestamp                 0
load_mw                   0
source_year               0
precipitation_mm          0
pressure_station_hpa      0
pressure_max_hpa          0
pressure_min_hpa          0
global_radiation_kj_m2    0
temperature_c             0
dew_point_c               0
temperature_max_c         0
temperature_min_c         0
dew_point_max_c           0
dew_point_min_c           0
humidity_max_pct          0
humidity_min_pct          0
humidity_pct              0
wind_gust_ms              0
wind_speed_ms             0
wind_direction_deg        0
station_count             0
dtype: int64

In [40]:
processed.to_parquet("data/processed/base.parquet", index=False)